[build]
publish = "public"   # публикуем именно папку public
# команда сборки НЕ нужна для статичного сайта
command = ""

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
  from = "http://questportal.uz/*"
  to   = "https://questportal.uz/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
